%% Transfer Learning FC 
% This script trains a fully connected layer on the feature space generated by Resnet50 avg-pool layer
%% Specification
clear
clc
close all
Path_to_script = pwd;
addpath(genpath(Path_to_script))
file_format = ""; % Specify the file format here (e.g tiff/tif/jpg)
Path_to_data = "";% Specify the path to the directory with labelled sub-directories  
Path_to_save = "";% Specify the path to directory in which the trained model will be saved 
n_class = 3; % Specify the number of classes in the classification
%% load the dataset
cd(Path_to_data)
fprintf("Loading images into an imds ...\n");
imds = imageDatastore(Path_to_data,'IncludeSubfolders',true,'LabelSource','foldernames');
[imdsTrain,imdsValidation,imdsTest] = splitEachLabel(imds,0.6,0.25,0.15,'randomized');
net = resnet50;
name = "resnet50_" + "FC"+".mat";
li = {'avg_pool'};

%% Training A Fully connected layer
% Choosing the network 
fprintf("Training the network ...\n");
[New_net,acc,preds,scores] = Train_net(imdsTrain,imdsValidation,imdsTest,net,li,n_class);

cd(Path_to_save)
save(name,'New_net');


